# __Цифровые инструменты финансиста__

## __День 1.__ Старт и знакомство с инструментами

### 7 апреля

### __5. SQL начало__

#### 5.1. Логика базы данных

Когда вы работаете в корпоративной среде, данные редко приходят к вам в виде готовой таблицы. Скорее всего их нужно будет забирать из базы данных (корпоративного хранилища). Для этого нужно начать мыслить запросами, а не кликами.

Показываем визуальную аналогию:
1. SELECT (выбрать столбцы) = выбор колонок в сводной таблице
2. FROM (откуда) = исходная таблица
3. WHERE (условие) = фильтр (например, показать только "Дебиторскую задолженность")
4. GROUP BY = группировка (сводная таблица) / ORDER BY = сортировка / JOIN = добавить другую таблицу / ...

...но не будем тратить время на детальный разбор логики и синтаксиса, будем ставить задачи ИИ для извлечения нужных нам данных при помощи SQL.

#### 5.2. Начнем с главного: подключение к базе

Просто спросим ИИ:

```prompt
Как в Jupyter ноутбуке подключиться к PostgreSQL?
```

...или более продвинутый вариант:

```prompt
## Базовые параметры
- Роль: финансовый аналитик на SQL
- Уровень: начинающий
- Температура: 0 (максимальная точность и предсказуемость)

## Входные данные
- хост с базой данных `miba-postgres-demo`
- имя базы данных `demo`
- имя пользователя `reader`
- пароль к базе данных `Miba2021`

## Задача
- подключиться к PostgreSQL
- предложи разные варианты подключения

## Технические ограничения
- код запускается в интерактивном ноутбуке Jupyter
```

__Вопрос на подумать:__ Что не так с этим проиптом? Подсказка - это касается вопросов информационной безопасности.

В ответе будет много вариантов, попробуем некоторые из них:
- через SQLAlchemy (для pandas)
- используя ipython-sql (магические команды)

Заодно надо спросить как собственно узнать, что лежит в БД (это и будет наш тестовый запрос):

```prompt
Как понять какие таблицы есть в БД?
```

__SQLAlchemy (для pandas)__

__Интересный факт:__ Команда для установки библиотеки в Jupyter Notebook имеет вид `!pip install имя_библиотеки`

In [1]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /opt/conda/lib/python3.12/site-packages (2.0.36)
Requirement already satisfied: psycopg2-binary in /opt/conda/lib/python3.12/site-packages (2.9.10)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy) (3.1.1)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [2]:
from sqlalchemy import create_engine
import pandas as pd
import os

# Создание connection string
# Создание connection string
POSTGRESQL_HOST = 'miba-postgres-demo'
CONNECT_DATA = 'postgresql://{}:{}@{}/{}'.format(
    os.environ['POSTGRESQL_USER'],
    os.environ['POSTGRESQL_PASSWORD'],
    POSTGRESQL_HOST,
    'demo'
)
engine = create_engine(CONNECT_DATA)

In [3]:
os.environ['POSTGRESQL_USER'], os.environ['POSTGRESQL_PASSWORD']

('reader', 'Miba2021')

In [4]:
# Чтение данных в DataFrame
df = pd.read_sql("SELECT * FROM pg_database", engine)
df

,oid,datname,datdba,encoding,datlocprovider,datistemplate,datallowconn,dathasloginevt,datconnlimit,datfrozenxid,datminmxid,dattablespace,datcollate,datctype,datlocale,daticurules,datcollversion,datacl
0,5,postgres,10,6,c,False,True,False,-1,744,1,1663,en_US.UTF-8,en_US.UTF-8,None,None,2.36,None
1,1,template1,10,6,c,True,True,False,-1,744,1,1663,en_US.UTF-8,en_US.UTF-8,None,None,2.36,"{=c/postgres,postgres=CTc/postgres}"
2,4,template0,10,6,c,True,False,False,-1,744,1,1663,en_US.UTF-8,en_US.UTF-8,None,None,None,"{=c/postgres,postgres=CTc/postgres}"
3,16384,demo,16385,6,c,False,True,False,-1,744,1,1663,en_US.UTF-8,en_US.UTF-8,None,None,2.36,"{=Tc/reader,reader=CTc/reader}"
4,16551,employees,10,6,c,False,True,False,-1,744,1,1663,en_US.UTF-8,en_US.UTF-8,None,None,2.36,"{=Tc/postgres,postgres=CTc/postgres,reader=c/p..."

In [5]:
# pandas
pd.read_sql("SELECT table_name FROM information_schema.tables", engine)

                table_name
0          boarding_passes
1           aircrafts_data
2                  flights
3            airports_data
4                    seats
..                     ...
198        foreign_servers
199  foreign_table_options
200         foreign_tables
201   user_mapping_options
202          user_mappings

[203 rows x 1 columns]

In [6]:
# Список всех таблиц
df_tables = pd.read_sql("""
    SELECT 
        table_schema,
        table_name,
        table_type
    FROM information_schema.tables
    WHERE table_schema NOT IN ('information_schema', 'pg_catalog')
    ORDER BY table_schema, table_name;
""", engine)
df_tables

   table_schema       table_name  table_type
0      bookings        aircrafts        VIEW
1      bookings   aircrafts_data  BASE TABLE
2      bookings         airports        VIEW
3      bookings    airports_data  BASE TABLE
4      bookings  boarding_passes  BASE TABLE
5      bookings         bookings  BASE TABLE
6      bookings          flights  BASE TABLE
7      bookings        flights_v        VIEW
8      bookings           routes        VIEW
9      bookings            seats  BASE TABLE
10     bookings   ticket_flights  BASE TABLE
11     bookings          tickets  BASE TABLE

__Используя ipython-sql (магические команды)__

Хорошая [статья про возможности интерактивных ноутбуков](https://habr.com/ru/companies/wunderfund/articles/316826/), там есть немного и про магические команды. А тут есть [оригинальный мануал про встроенные магические команды](https://ipython.readthedocs.io/en/stable/interactive/magics.html), это действительно мощный и полезный инструмент.

In [7]:
!pip install ipython-sql

Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl.metadata (17 kB)
Collecting prettytable (from ipython-sql)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: ipython in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (8.30.0)
Requirement already satisfied: sqlalchemy>=2.0 in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (2.0.36)
Collecting sqlparse (from ipython-sql)
  Downloading sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: six in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy>=2.0->ipython-sql) (3.1.1)
Requirement already satisfied: decorator in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (3.0.48)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (2.18.0)
Requirement already satisfied: stack_data in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (0.6.2)
Requirement already satisfied: traitlets>=5.13.0 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.12/site-packages (from prettytable->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/conda/lib/python3.12/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.12/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython->ipython-sql) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure-eval in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython->ipython-sql) (0.2.3)
Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading sqlparse-0.5.5-py3-none-any.whl (46 kB)
Installing collected packages: sqlparse, prettytable, ipython-sql
Successfully installed ipython-sql-0.5.0 prettytable-3.17.0 sqlparse-0.5.5

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

Enable `sql` in Jupyter notebook cells:

In [8]:
%load_ext sql

In [9]:
# There is a bug with `sql` magic, have to fix it
# in some environments e.g. in `Data Science environment`.
# So if you meet `KeyError: 'DEFAULT'` error 
# use the code below:

%config SqlMagic.style = '_DEPRECATED_DEFAULT'

Connection data string to be used later:

In [10]:
import os

POSTGRESQL_HOST = 'miba-postgres-demo'
CONNECT_DATA = 'postgresql://{}:{}@{}/{}'.format(
    os.environ['POSTGRESQL_USER'],
    os.environ['POSTGRESQL_PASSWORD'],
    POSTGRESQL_HOST,
    'demo'
)

Let's look at all databases in PostgreSQL. SQL query can be done after the connection with `%%sql` magic command:

In [11]:
%%sql $CONNECT_DATA
    SELECT * FROM pg_database

5 rows affected.

[(5, 'postgres', 10, 6, 'c', False, True, False, -1, '744', '1', 1663, 'en_US.UTF-8', 'en_US.UTF-8', None, None, '2.36', None),
 (1, 'template1', 10, 6, 'c', True, True, False, -1, '744', '1', 1663, 'en_US.UTF-8', 'en_US.UTF-8', None, None, '2.36', '{=c/postgres,postgres=CTc/postgres}'),
 (4, 'template0', 10, 6, 'c', True, False, False, -1, '744', '1', 1663, 'en_US.UTF-8', 'en_US.UTF-8', None, None, None, '{=c/postgres,postgres=CTc/postgres}'),
 (16384, 'demo', 16385, 6, 'c', False, True, False, -1, '744', '1', 1663, 'en_US.UTF-8', 'en_US.UTF-8', None, None, '2.36', '{=Tc/reader,reader=CTc/reader}'),
 (16551, 'employees', 10, 6, 'c', False, True, False, -1, '744', '1', 1663, 'en_US.UTF-8', 'en_US.UTF-8', None, None, '2.36', '{=Tc/postgres,postgres=CTc/postgres,reader=c/postgres}')]

Connect string can be omitted (just use `%sql` NOT the `%%sql`) if connection is done earlier. Now will get all tables in `demo` database:

In [12]:
%sql SELECT tablename AS table FROM pg_tables WHERE tablename !~ '^(pg_|sql_)'

 * postgresql://reader:***@miba-postgres-demo/demo
8 rows affected.

[('boarding_passes',),
 ('aircrafts_data',),
 ('flights',),
 ('airports_data',),
 ('seats',),
 ('tickets',),
 ('ticket_flights',),
 ('bookings',)]

In [13]:
CONNECT_DATA = 'postgresql://{}:{}@{}/{}'.format(
    os.environ['POSTGRESQL_USER'],
    os.environ['POSTGRESQL_PASSWORD'],
    POSTGRESQL_HOST,
    'employees'
)

In [14]:
%%sql $CONNECT_DATA
    SELECT * FROM pg_database

5 rows affected.

[(5, 'postgres', 10, 6, 'c', False, True, False, -1, '744', '1', 1663, 'en_US.UTF-8', 'en_US.UTF-8', None, None, '2.36', None),
 (1, 'template1', 10, 6, 'c', True, True, False, -1, '744', '1', 1663, 'en_US.UTF-8', 'en_US.UTF-8', None, None, '2.36', '{=c/postgres,postgres=CTc/postgres}'),
 (4, 'template0', 10, 6, 'c', True, False, False, -1, '744', '1', 1663, 'en_US.UTF-8', 'en_US.UTF-8', None, None, None, '{=c/postgres,postgres=CTc/postgres}'),
 (16384, 'demo', 16385, 6, 'c', False, True, False, -1, '744', '1', 1663, 'en_US.UTF-8', 'en_US.UTF-8', None, None, '2.36', '{=Tc/reader,reader=CTc/reader}'),
 (16551, 'employees', 10, 6, 'c', False, True, False, -1, '744', '1', 1663, 'en_US.UTF-8', 'en_US.UTF-8', None, None, '2.36', '{=Tc/postgres,postgres=CTc/postgres,reader=c/postgres}')]

In [15]:
%sql SELECT tablename AS table FROM pg_tables WHERE tablename !~ '^(pg_|sql_)'

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
6 rows affected.

[('employee',),
 ('department_employee',),
 ('department',),
 ('department_manager',),
 ('salary',),
 ('title',)]

In [16]:
%sql

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees

#### 5.3. Готовимся промптить

In [17]:
%sql SELECT DISTINCT table_schema FROM information_schema.tables WHERE table_type = 'BASE TABLE' ORDER BY table_schema;

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
3 rows affected.

[('employees',), ('information_schema',), ('pg_catalog',)]

In [18]:
%sql SELECT schemaname, tablename FROM pg_tables WHERE schemaname = 'employees'  ORDER BY schemaname, tablename LIMIT 20;

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
6 rows affected.

[('employees', 'department'),
 ('employees', 'department_employee'),
 ('employees', 'department_manager'),
 ('employees', 'employee'),
 ('employees', 'salary'),
 ('employees', 'title')]

In [19]:
# Сохраняем список таблиц в переменную Python
tables = %sql SELECT tablename FROM pg_tables WHERE schemaname = 'employees' ORDER BY tablename;
table_list = [row.tablename for row in tables]
print("Найденные таблицы в схеме employees:", table_list)
print(f"Всего таблиц: {len(table_list)}")

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
6 rows affected.
Найденные таблицы в схеме employees: ['department', 'department_employee', 'department_manager', 'employee', 'salary', 'title']
Всего таблиц: 6

In [20]:
%%sql 

SELECT table_name,
    column_name,
    data_type,
    is_nullable 
FROM information_schema.columns WHERE table_schema = 'employees' ORDER BY table_name, ordinal_position;

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
24 rows affected.

[('department', 'id', 'character', 'NO'),
 ('department', 'dept_name', 'character varying', 'NO'),
 ('department_employee', 'employee_id', 'bigint', 'NO'),
 ('department_employee', 'department_id', 'character', 'NO'),
 ('department_employee', 'from_date', 'date', 'NO'),
 ('department_employee', 'to_date', 'date', 'NO'),
 ('department_manager', 'employee_id', 'bigint', 'NO'),
 ('department_manager', 'department_id', 'character', 'NO'),
 ('department_manager', 'from_date', 'date', 'NO'),
 ('department_manager', 'to_date', 'date', 'NO'),
 ('employee', 'id', 'bigint', 'NO'),
 ('employee', 'birth_date', 'date', 'NO'),
 ('employee', 'first_name', 'character varying', 'NO'),
 ('employee', 'last_name', 'character varying', 'NO'),
 ('employee', 'gender', 'USER-DEFINED', 'NO'),
 ('employee', 'hire_date', 'date', 'NO'),
 ('salary', 'employee_id', 'bigint', 'NO'),
 ('salary', 'amount', 'bigint', 'NO'),
 ('salary', 'from_date', 'date', 'NO'),
 ('salary', 'to_date', 'date', 'NO'),
 ('title', 'employee_id', 'bigint', 'NO'),
 ('title', 'title', 'character varying', 'NO'),
 ('title', 'from_date', 'date', 'NO'),
 ('title', 'to_date', 'date', 'YES')]

In [21]:
%%sql 

SELECT 
    c.relname AS table_name,
    a.attname AS column_name,
    pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
    NOT a.attnotnull AS is_nullable
FROM pg_catalog.pg_class c
JOIN pg_catalog.pg_attribute a ON c.oid = a.attrelid
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'employees'
    AND c.relkind = 'r'  -- 'r' = обычная таблица
    AND a.attnum > 0     -- исключаем системные колонки
    AND NOT a.attisdropped
ORDER BY c.relname, a.attnum;

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
24 rows affected.

[('department', 'id', 'character(4)', False),
 ('department', 'dept_name', 'character varying(40)', False),
 ('department_employee', 'employee_id', 'bigint', False),
 ('department_employee', 'department_id', 'character(4)', False),
 ('department_employee', 'from_date', 'date', False),
 ('department_employee', 'to_date', 'date', False),
 ('department_manager', 'employee_id', 'bigint', False),
 ('department_manager', 'department_id', 'character(4)', False),
 ('department_manager', 'from_date', 'date', False),
 ('department_manager', 'to_date', 'date', False),
 ('employee', 'id', 'bigint', False),
 ('employee', 'birth_date', 'date', False),
 ('employee', 'first_name', 'character varying(14)', False),
 ('employee', 'last_name', 'character varying(16)', False),
 ('employee', 'gender', 'employees.employee_gender', False),
 ('employee', 'hire_date', 'date', False),
 ('salary', 'employee_id', 'bigint', False),
 ('salary', 'amount', 'bigint', False),
 ('salary', 'from_date', 'date', False),
 ('salary', 'to_date', 'date', False),
 ('title', 'employee_id', 'bigint', False),
 ('title', 'title', 'character varying(50)', False),
 ('title', 'from_date', 'date', False),
 ('title', 'to_date', 'date', True)]

In [22]:
%sql SELECT * FROM employees.department LIMIT 3;

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
3 rows affected.

[('d009', 'Customer Service'), ('d005', 'Development'), ('d002', 'Finance')]

In [23]:
%sql SELECT * FROM employees.department_employee LIMIT 3;

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
3 rows affected.

[(10001, 'd005', datetime.date(1986, 6, 26), datetime.date(9999, 1, 1)),
 (10002, 'd007', datetime.date(1996, 8, 3), datetime.date(9999, 1, 1)),
 (10003, 'd004', datetime.date(1995, 12, 3), datetime.date(9999, 1, 1))]

In [24]:
%sql SELECT * FROM employees.employee LIMIT 3;

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
3 rows affected.

[(10001, datetime.date(1953, 9, 2), 'Georgi', 'Facello', 'M', datetime.date(1986, 6, 26)),
 (10002, datetime.date(1964, 6, 2), 'Bezalel', 'Simmel', 'F', datetime.date(1985, 11, 21)),
 (10003, datetime.date(1959, 12, 3), 'Parto', 'Bamford', 'M', datetime.date(1986, 8, 28))]

In [25]:
%sql SELECT * FROM employees.salary LIMIT 3;

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
3 rows affected.

[(10001, 60117, datetime.date(1986, 6, 26), datetime.date(1987, 6, 26)),
 (10001, 62102, datetime.date(1987, 6, 26), datetime.date(1988, 6, 25)),
 (10001, 66074, datetime.date(1988, 6, 25), datetime.date(1989, 6, 25))]

In [26]:
%sql SELECT * FROM employees.title LIMIT 3;

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
3 rows affected.

[(10001, 'Senior Engineer', datetime.date(1986, 6, 26), datetime.date(9999, 1, 1)),
 (10002, 'Staff', datetime.date(1996, 8, 3), datetime.date(9999, 1, 1)),
 (10003, 'Senior Engineer', datetime.date(1995, 12, 3), datetime.date(9999, 1, 1))]

#### 5.4. Составим промпт для решения SQL задач

In [27]:
%%sql 

SELECT 
    e.id AS employee_id,
    e.first_name,
    e.last_name,
    s.amount AS salary
FROM employees.employee e
INNER JOIN employees.salary s ON e.id = s.employee_id
WHERE s.to_date = '9999-01-01'  -- текущая зарплата
ORDER BY s.amount DESC
LIMIT 5;

   postgresql://reader:***@miba-postgres-demo/demo
 * postgresql://reader:***@miba-postgres-demo/employees
5 rows affected.

[(43624, 'Tokuyasu', 'Pesch', 158220),
 (254466, 'Honesty', 'Mukaidono', 156286),
 (47978, 'Xiahua', 'Whitcomb', 155709),
 (253939, 'Sanjai', 'Luders', 155513),
 (109334, 'Tsutomu', 'Alameldin', 155190)]